[build]
cmd = "dotnet publish BookReviews.API/BookReviews.API.csproj -c Release -o ./out"

[start]
cmd = "cd ./out && dotnet BookReviews.API.dll"

[env]
DOTNET_VERSION = "9.0"
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"