[phases.setup]
nixPkgs = ['dotnet', 'aspnetcore-runtime']

[phases.build]
cmds = [
    'dotnet restore BookReviews.API/BookReviews.API.csproj',
    'dotnet publish BookReviews.API/BookReviews.API.csproj -c Release -o out'
]

[phases.start]
cmds = ['dotnet BookReviews.API.dll']

[env]
DOTNET_VERSION = '9.0'