name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Display directory structure
      run: find . -type f -name "*.sln" -o -name "*.csproj" | sort
        
    - name: Restore dependencies
      run: dotnet restore BookReviews.API/BookReviews.API.sln
      
    - name: Build
      run: dotnet build BookReviews.API/BookReviews.API.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test BookReviews.API/BookReviews.API.sln --no-build --verbosity normal --configuration Release || true

  deploy:
    name: Deploy to Railway
    needs: build-and-test
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build and Publish API
      run: |
        # Instalamos .NET en el contenedor de Railway CLI
        apt-get update
        apt-get install -y wget apt-transport-https
        wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        apt-get update
        apt-get install -y dotnet-sdk-9.0
        
        # Muestra la estructura de directorios para depuración
        find . -type f -name "*.sln" -o -name "*.csproj" | sort
        
        # Compilar y publicar
        dotnet restore BookReviews.API/BookReviews.API.sln
        dotnet publish BookReviews.API/BookReviews.API/BookReviews.API.csproj -c Release -o ./publish
      
    - name: Deploy to Railway
      run: |
        # Usar Railway CLI para desplegar (ya está instalado en la imagen)
        railway up --service "Project-.Net-Book-reviews"
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}