name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Actualizado a .NET 9.0
        
    - name: Display directory structure
      run: find . -type f -name "*.sln" -o -name "*.csproj" | sort
        
    - name: Restore dependencies
      run: dotnet restore BookReviews.API/BookReviews.API.sln
      
    - name: Build
      run: dotnet build BookReviews.API/BookReviews.API.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test BookReviews.API/BookReviews.API.sln --no-build --verbosity normal --configuration Release || true

  deploy:
    name: Deploy to Railway
    needs: build-and-test
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Actualizado a .NET 9.0
        
    - name: Install Railway CLI
      run: npm i -g @railway/cli
      
    - name: Build and Publish API
      run: |
        dotnet restore BookReviews.API/BookReviews.API.sln
        dotnet publish BookReviews.API/BookReviews.API.csproj -c Release -o ./publish
      
    - name: Deploy to Railway
      working-directory: ./publish
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}